# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: true
dist: trusty
os:
  - linux
  # - osx
julia:
  - release
  # - nightly
notifications:
  email: false
branches:
  only: master
before_install:
  - sudo apt-get install gcc gfortran python-numpy -y

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Robocon2017Tutorial"); Pkg.test("Robocon2017Tutorial"; coverage=true)'
